# test HTTP requests
### use with: HTTP client extension

@apiurl = http://localhost:3000/api
@token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMSwidXNlcm5hbWUiOiJodXB1IiwiZW1haWwiOiJodXB1QGV4YW1wbGUuZmkiLCJjcmVhdGVkX2F0IjoiMjAyNi0wMy0wMlQxNjoyNTo0OC4wMDBaIiwidXNlcl9sZXZlbCI6InJlZ3VsYXIiLCJpYXQiOjE3NzI2MjQ3MDcsImV4cCI6MTc3MjcxMTEwN30.sNj8p1W8iQO7M19GOUJTHNW-kdwdkf18Kk8E0dEFfZ8

### Get all items
GET {{apiurl}}/items


### Add new item
POST {{apiurl}}/items
Content-Type: application/json

{
  "name": "Appelsiini"
}

### Get item by ID
GET {{apiurl}}/items/1

### delete route for item
DELETE {{apiurl}}/items/1

### Put route for item
PUT {{apiurl}}/items/1
Content-Type: application/json

{
  "name": "Porkkana"
}

// user endpoints

### Get all users
GET {{apiurl}}/users

### Register new user
POST {{apiurl}}/users
Content-Type: application/json


{
  "username": "hupu",
  "password": "hupuankka2026",
  "email": "hupu@example.fi"
}


### Register new user FAIL when email missing
POST {{apiurl}}/users
Content-Type: application/json


{
  "username": "roope",
  "password": "ankka"
}

### User login
POST {{apiurl}}/users/login
Content-Type: application/json

{
  "username": "hupu",
  "password": "hupuankka2026"
}

### Get user info by token
GET {{apiurl}}/users/me
Authorization: Bearer {{token}}


### Diary entry endpoints

### Get all entries (by user id in token)
GET {{apiurl}}/entries
Authorization: Bearer {{token}}

### GET entry by id
GET {{apiurl}}/entries/9


### Delete entry by id
DELETE {{apiurl}}/entries/7
Authorization: Bearer {{token}}

### Post new entry
POST {{apiurl}}/entries
Content-Type: application/json
Authorization: Bearer {{token}}

{ 
  "user_id": 11,
  "entry_date": "2026-02-04",
  "mood": "really happy",
  "weight": 66,
  "sleep_hours": 5,
  "steps": 11800,
  "calories_eaten": 3000,
  "calories_burned": 3800,
  "notes": "normipäivä"
}