# test HTTP requests
### use with: HTTP client extension

@apiurl = http://localhost:3000/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo4LCJ1c2VybmFtZSI6InJvb3BlIiwiZW1haWwiOiJhbmtrYUBleGFtcGxlLmNvbSIsImNyZWF0ZWRfYXQiOiIyMDI2LTAyLTI1VDA4OjI2OjAxLjAwMFoiLCJ1c2VyX2xldmVsIjoicmVndWxhciIsImlhdCI6MTc3MjA5MzAxNiwiZXhwIjoxNzcyMTc5NDE2fQ.6CTyKlbwnj_iHB0XsYeVy32S3WcUSBTvznvSR0b-GYg

### Get all items
GET {{apiurl}}/items


### Add new item
POST {{apiurl}}/items
Content-Type: application/json

{
  "name": "Appelsiini"
}

### Get item by ID
GET {{apiurl}}/items/1

### delete route for item
DELETE {{apiurl}}/items/1

### Put route for item
PUT {{apiurl}}/items/1
Content-Type: application/json

{
  "name": "Porkkana"
}

// user endpoints

### Get all users
GET {{apiurl}}/users

### Register new user
POST {{apiurl}}/users
Content-Type: application/json


{
  "username": "roope",
  "password": "ankka",
  "email": "ankka@example.com"
}


### Register new user FAIL when email missing
POST {{apiurl}}/users
Content-Type: application/json


{
  "username": "roope",
  "password": "ankka"
}

### User login
POST {{apiurl}}/users/login
Content-Type: application/json

{
  "username": "roope",
  "password": "ankka"
}

### Get user info by token
GET {{apiurl}}/users/me
Authorization: Bearer {{token}}


### Diary entry endpoints

### Get all entries (by user id in token)
GET {{apiurl}}/entries
Authorization: Bearer {{token}}

### GET entry by id
GET {{apiurl}}/entries/3


### Delete entry by id
DELETE {{apiurl}}/entries/6
Authorization: Bearer {{token}}

### Post new entry
POST {{apiurl}}/entries
Content-Type: application/json
Authorization: Bearer {{token}}

{ 
  "user_id": 8,
  "entry_date": "2026-02-04",
  "mood": "really happy",
  "weight": 66,
  "sleep_hours": 5,
  "steps": 10000,
  "calories_eaten": 2000,
  "calories_burned": 3000,
  "notes": "normipäivä"
}